// <auto-generated />
using CoWorker.Models.Blog;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace CoWorker.Models.Blogs.Migrations
{
    [DbContext(typeof(BlogDbContext))]
    partial class BlogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoWorker.Models.Blog.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<DateTimeOffset>("CreateDate");

                    b.Property<string>("Creator");

                    b.Property<string>("Description");

                    b.Property<string>("Modifier");

                    b.Property<DateTimeOffset>("ModifyDate");

                    b.Property<string>("Source");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("CoWorker.Models.Blog.PostRelated", b =>
                {
                    b.Property<Guid>("CurrentId");

                    b.Property<DateTime>("EndDate");

                    b.Property<int>("Level");

                    b.Property<Guid>("ParentId")
                        .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000001"));

                    b.Property<DateTime>("StartDate");

                    b.Property<Guid>("UserId")
                        .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000001"));

                    b.HasKey("CurrentId");

                    b.HasAlternateKey("UserId");

                    b.HasIndex("ParentId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Related");
                });

            modelBuilder.Entity("CoWorker.Models.Blog.Post", b =>
                {
                    b.HasOne("CoWorker.Models.Blog.PostRelated")
                        .WithOne("Current")
                        .HasForeignKey("CoWorker.Models.Blog.Post", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CoWorker.Models.Blog.PostRelated", b =>
                {
                    b.HasOne("CoWorker.Models.Blog.PostRelated", "Parent")
                        .WithMany("Posts")
                        .HasForeignKey("CurrentId")
                        .HasPrincipalKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
